# Generated by Django 5.0.3 on 2024-04-07 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="overtime",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leave_requests",
                to="myApp.employee",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performance",
            name="performance_rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performance",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performances_reviewed",
                to="myApp.employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="clock_out",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="myApp.employee",
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances_received",
                to="myApp.employee",
            ),
        ),
    ]
