# Generated by Django 5.0.3 on 2024-04-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0003_leavebalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="total_leave_days",
            field=models.IntegerField(default=0),
        ),
    ]
